language: cpp

matrix:
  include:
  - os: linux
    env:
    - NAME="Ubuntu 14.04"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    dist: trusty
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - gcc-7
  - os: linux
    dist: xenial
    env:
    - NAME="Ubuntu 16.04"
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - gcc-7
  - os: linux
    dist: trusty
    env:
    - NAME="Ubuntu 14.04"
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - g++-6
        - gcc-6
  - os: linux
    dist: xenial
    env:
    - NAME="Ubuntu 16.04"
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - g++-6
        - gcc-6

  - os: linux
    dist: xenial
    addons:
      apt:
        sources:
          - llvm-toolchain-trusty-5.0
        packages:
          - clang-5.0
    env:
      - NAME="Ubuntu 16.04"
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

  - os: linux
    dist: trusty
    addons:
      apt:
        sources:
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
    env:
      - NAME="Ubuntu 14.04"
      - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
- eval "${MATRIX_EVAL}"

script:
- cmake . -Bbuild && cd build && make -j8
- ./bin/run_tests