
language: cpp

matrix:
  include:
  - os: linux
    env: NAME="Ubuntu 14.04 - g++-7"
    dist: trusty
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
  - os: linux
    dist: xenial
    env: NAME="Ubuntu 16.04 - g++-7"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
  - os: linux
    dist: trusty
    env: NAME="Ubuntu 14.04 - clang-5.0"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0
  - os: linux
    dist: xenial
    env: NAME="Ubuntu 16.04 - clang-5.0"
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        packages:
        - clang-5.0


script:
- cmake . -Bbuild && cd build && make -j8
- ./bin/run_tests
